### ISSUE TITLE
Kindle for PC version to use

### ISSUE THREAD

**Issue by Cameleonbates** [ToofDerling/CbzMage#34]
Hi,

Great program!  I'm not super great with cmd, but I was able to get it to work!  Ever since Comixology went away, I've been looking for a means to back up my comics without 2 page spreads shrinking down!  Your program fixes that, so thank you very much!

I do have a question though.  When I started using your program today, I was using an older version of Kindle for PC (1.38.0 (65290), and was able to back up my comics just fine.  Except when it came to newer comics.  Those ones told me I had to upgrade to the latest version to be able to download the comic (Such as Void Rivals #6 or Wonder Woman #3).  So I downloaded the newst version of Kindle for PC (2.2.0 (07623), and now when I download a comic, even ones I was able to successfully download on the older version of Kindle for PC, I get the following error:

Error reading metadate from <pathway to where I save my comics> MobiMetadataException: Did not get expected MOBI identifier.

Are the books downloaded using the new version of Kindle for PC not compatible with CbzMage?

Thanks,

**Comment by ToofDerling** [comment]
Yeah, Kdl 2.2.0 introduces drm for downloaded comics and that's why you get the CbzMage error. There's no way to remove Kdl drm - the "big secret" of CbzMage was that, until now, there was no drm at all for Cmxlgy books.

Kdl 2.0.0 still works though (and you can find downloads of that version with a little searching). I downgraded to 2.0.0 and bought a couple of books (one of them was Void Rivals #6), they both downloaded and converted fine. Note that if you downgrade you should turn off the sneaky "Automatically install updates" option in Kdl.

2.0.0 will only work until next time you're required to update to the latest version to download the comics you bought, Hopefully that will be a while...

**Comment by Cameleonbates** [comment]
Hi!  Thanks for your response.  I just a similar solution.  Apparently, the old version I was using was SO old that Amazon wouldn't allow downloads to occur for releases past 1/3/23 (needs to be 1.39 or above).  I downloaded 1.39 and that seems to be working fine.  Good to know that 2.0.0 works if I have problems though.  Thanks!
